In [2]:
import pandas as pd
import numpy as np

In [7]:
customers = pd.read_csv("../data/raw/customers_raw.csv")
products = pd.read_csv("../data/raw/products_raw.csv")
orders = pd.read_csv("../data/raw/orders_raw.csv")
marketing = pd.read_csv("../data/raw/marketing_raw.csv")
inventory = pd.read_csv("../data/raw/inventory_raw.csv")

1. Inspections

In [9]:
datasets  = {
    "Customers" : customers,
    "Orders" : orders,
    "Products" : products,
    "Marketing" : marketing,
    "Inventory" : inventory
}

for name, df in datasets.items():
    print(name, ":", df.shape)

Customers : (50000, 9)
Orders : (50000, 14)
Products : (50000, 9)
Marketing : (50000, 14)
Inventory : (50000, 10)

2. Inspect the first record

In [11]:
orders.head()
orders.tail()

,order_id,customer_id,product_id,order_date,quantity,unit_price,discount_pct,revenue,shipping_cost,payment_method,order_status,customer_rating,estimated_cost,profit
49995,ORD349996,CUST121839,PROD208790,2025-09-15 04:12:28,5,18577.66,0.05,88243.88,161.74,Net Banking,Delivered,3.9,74204.15,13877.99
49996,ORD349997,CUST112544,PROD213782,2026-04-09 08:08:45,4,5568.52,0.15,18932.97,106.52,Debit Card,Delivered,3.0,18486.28,340.17
49997,ORD349998,CUST114304,PROD210200,2024-07-16 07:47:43,3,524.00,0.00,1572.00,124.52,Credit Card,Delivered,2.1,1446.06,1.42
49998,ORD349999,CUST111905,PROD224118,2025-12-21 02:14:06,4,12904.25,0.15,43874.45,162.03,Wallet,Delivered,2.0,45853.56,-2141.14
49999,ORD350000,CUST147545,PROD222045,2026-05-10 04:43:21,5,4121.26,0.15,17515.36,41.19,Wallet,Delivered,1.8,16242.30,1231.87

3. Inspecting a Random sample

In [12]:
orders.sample(10, random_state=42)

,order_id,customer_id,product_id,order_date,quantity,unit_price,discount_pct,revenue,shipping_cost,payment_method,order_status,customer_rating,estimated_cost,profit
33553,ORD333554,CUST107882,PROD206915,2025-10-14 09:44:41,1,7282.73,0.05,6918.59,194.74,COD,Delivered,4.4,6469.10,254.75
9427,ORD309428,CUST145182,PROD235730,2026-02-18 15:41:11,1,181.09,0.25,135.82,91.34,UPI,Delivered,1.2,158.68,-114.20
199,ORD300200,CUST111720,PROD224167,2025-07-23 05:11:12,2,23709.17,0.15,40305.59,259.10,COD,Delivered,1.8,38059.98,1986.51
12447,ORD312448,CUST141018,PROD202895,2025-06-19 15:52:22,1,33713.05,0.10,30341.75,180.78,Wallet,Delivered,4.9,24965.72,5195.25
39489,ORD339490,CUST120443,PROD241884,2026-06-19 00:22:00,4,18065.98,0.10,65037.53,117.30,UPI,Delivered,4.9,51638.36,13281.87
42724,ORD342725,CUST121680,PROD209515,2025-11-01 05:43:30,3,4410.45,0.20,10585.08,109.52,Wallet,Delivered,3.6,10308.21,167.35
10822,ORD310823,CUST113982,PROD248772,2024-08-29 02:38:05,5,29659.40,0.15,126052.45,281.31,Net Banking,Delivered,4.8,127651.40,-1880.26
49498,ORD349499,CUST143824,PROD217652,2026-06-14 02:01:13,2,7757.71,0.05,14739.65,71.65,UPI,Delivered,4.9,14007.62,660.38
4144,ORD304145,CUST125498,PROD227583,2026-04-22 17:40:10,3,28520.10,0.00,85560.30,194.16,Credit Card,Delivered,4.4,67285.20,18080.94
36958,ORD336959,CUST147764,PROD205263,2024-07-14 02:49:29,5,1758.01,0.15,7471.54,288.69,UPI,Delivered,3.5,6840.10,342.75

4. Understand the structure

In [13]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         50000 non-null  object
 1   customer_id      49850 non-null  object
 2   product_id       50000 non-null  object
 3   order_date       50000 non-null  object
 4   quantity         50000 non-null  int64
 5   unit_price       50000 non-null  float64
 6   discount_pct     50000 non-null  float64
 7   revenue          50000 non-null  float64
 8   shipping_cost    50000 non-null  float64
 9   payment_method   50000 non-null  object
 10  order_status     50000 non-null  object
 11  customer_rating  49700 non-null  float64
 12  estimated_cost   50000 non-null  float64
 13  profit           50000 non-null  float64
dtypes: float64(7), int64(1), object(6)
memory usage: 5.3+ MB

5. Check datatypes

In [15]:
orders.dtypes

order_id            object
customer_id         object
product_id          object
order_date          object
quantity             int64
unit_price         float64
discount_pct       float64
revenue            float64
shipping_cost      float64
payment_method      object
order_status        object
customer_rating    float64
estimated_cost     float64
profit             float64
dtype: object

6. Missing Vales Inspection

In [33]:
orders.isnull().sum()

order_id             0
customer_id        150
product_id           0
order_date           0
quantity             0
unit_price           0
discount_pct         0
revenue              0
shipping_cost        0
payment_method       0
order_status         0
customer_rating    300
estimated_cost       0
profit               0
dtype: int64

In [34]:
customers.isnull().sum()

customer_id           0
customer_name         0
age                 400
gender                0
city                200
state                 0
signup_date           0
customer_segment      0
preferred_device      0
dtype: int64

In [35]:
products.isnull().sum()

product_id           0
product_name         0
brand                0
category             0
sub_category         0
cost_price           0
selling_price        0
stock_quantity     300
supplier_rating      0
dtype: int64

In [36]:
marketing.isnull().sum()

campaign_id            0
campaign_date          0
campaign_name          0
campaign_type        200
channel                0
target_segment         0
impressions            0
clicks               200
conversions            0
spend                  0
revenue_generated      0
ctr                    0
conversion_rate        0
roas                   0
dtype: int64

In [37]:
inventory.isnull().sum()

inventory_id        0
snapshot_date       0
product_id          0
warehouse           0
opening_stock       0
units_received      0
units_sold          0
damaged_units       0
closing_stock     250
stock_status        0
dtype: int64

7. duplicate inspection

In [43]:
customers.duplicated().sum()
customers["customer_id"].duplicated().sum()

np.int64(0)

In [39]:
orders.duplicated().sum()

np.int64(0)

In [40]:
products.duplicated().sum()

np.int64(0)

In [41]:
inventory.duplicated().sum()

np.int64(0)

In [42]:
marketing.duplicated().sum()

np.int64(0)

In [21]:
orders["order_id"].duplicated().sum()

np.int64(0)

8. Numerical Inspection

In [22]:
orders.describe()

,quantity,unit_price,discount_pct,revenue,shipping_cost,customer_rating,estimated_cost,profit
count,50000.00000,50000.000000,50000.000000,5.000000e+04,50000.000000,49700.000000,50000.000000,50000.000000
mean,2.97826,18678.071791,0.107418,5.178011e+04,159.734487,3.009300,44718.566200,4996.011103
std,1.45152,10923.258196,0.078294,6.969567e+04,80.735711,1.155418,35479.376788,8553.166779
min,-5.00000,104.120000,0.000000,7.300000e+01,20.000000,1.000000,81.220000,-35135.740000
25%,2.00000,9293.880000,0.050000,1.809142e+04,89.500000,2.000000,16467.822500,73.325000
50%,3.00000,18456.575000,0.100000,3.869921e+04,159.755000,3.000000,34991.440000,2528.645000
75%,4.00000,27837.085000,0.150000,7.374751e+04,229.785000,4.000000,66045.912500,7875.702500
max,5.00000,42504.260000,0.300000,3.481290e+06,300.000000,5.000000,149951.650000,61967.540000

In [23]:
products.describe()

         cost_price  selling_price  stock_quantity  supplier_rating
count  50000.000000   50000.000000    49700.000000     50000.000000
mean   14885.200172   18754.014309      247.878732         3.753492
std     8833.220842   10905.905092      144.005246         0.722875
min   -29953.920000      89.440000        0.000000         2.500000
25%     7480.405000    9390.547500      124.000000         3.100000
50%    14916.030000   18594.350000      247.000000         3.800000
75%    22449.387500   27904.187500      372.000000         4.400000
max    29999.560000   42504.260000      499.000000         5.000000

9. Buisness rule Validation

In [24]:
orders[orders["quantity"] <= 0]

,order_id,customer_id,product_id,order_date,quantity,unit_price,discount_pct,revenue,shipping_cost,payment_method,order_status,customer_rating,estimated_cost,profit
57,ORD300058,CUST147608,PROD247560,2024-04-09 12:37:03,-3,13877.41,0.00,41632.23,274.10,cod,Shipped,2.8,30169.68,11188.45
447,ORD300448,CUST149105,PROD232684,2024-03-03 07:05:13,-4,13760.55,0.15,46785.87,267.99,UPI,Cancelled,2.9,40934.20,5583.68
1294,ORD301295,CUST125292,PROD204547,2025-01-11 22:56:01,-5,14689.64,0.10,66103.38,150.47,Debit Card,Delivered,1.2,57631.45,8321.46
1349,ORD301350,CUST100062,PROD233025,2025-09-23 19:12:41,-4,28379.63,0.05,107842.59,96.73,Net Banking,Returned,1.3,103348.96,4396.90
1465,ORD301466,CUST122332,PROD213398,2024-05-05 02:00:28,-1,1464.67,0.00,1464.67,51.99,Net Banking,Delivered,3.8,1095.07,317.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48102,ORD348103,CUST131775,PROD233363,2024-08-22 03:41:00,-5,40297.12,0.15,171262.76,129.91,Net Banking,Delivered,3.7,149939.25,21193.60
48166,ORD348167,CUST118684,PROD246283,2025-05-12 17:11:05,-1,19929.16,0.05,18932.70,267.37,COD,Delivered,4.5,16388.01,2277.32
49029,ORD349030,CUST148438,PROD228796,2024-03-14 19:03:49,-4,19170.07,0.05,72846.27,174.99,COD,Delivered,1.1,57982.28,14689.00
49270,ORD349271,CUST124527,PROD234831,2024-09-01 22:45:42,-5,14171.04,0.15,60226.92,140.38,Credit Card,Delivered,1.5,64960.00,-4873.46
49855,ORD349856,CUST128582,PROD232267,2024-03-15 03:01:08,-5,3803.91,0.10,17117.60,35.25,Debit Card,Cancelled,1.9,16633.20,449.15

In [25]:
orders[orders["revenue"] <= 0]

Empty DataFrame
Columns: [order_id, customer_id, product_id, order_date, quantity, unit_price, discount_pct, revenue, shipping_cost, payment_method, order_status, customer_rating, estimated_cost, profit]
Index: []

In [26]:
orders[
    (orders["discount_pct"] < 1) |
    (orders["discount_pct"] > 1)
]

,order_id,customer_id,product_id,order_date,quantity,unit_price,discount_pct,revenue,shipping_cost,payment_method,order_status,customer_rating,estimated_cost,profit
0,ORD300001,CUST118649,PROD221229,2025-11-24 03:26:44,3,7322.73,0.15,18672.96,240.34,debit card,Returned,3.7,19696.68,-1264.06
1,ORD300002,CUST111951,PROD201741,2026-06-04 12:57:30,3,6005.61,0.15,15314.31,90.75,upi,Delivered,1.2,16400.28,-1176.72
2,ORD300003,CUST115785,PROD231342,2024-12-26 00:15:18,5,2941.24,0.30,10294.34,162.06,credit card,Delivered,4.0,12839.75,-2707.47
3,ORD300004,CUST147507,PROD219074,2025-11-21 15:04:31,4,14981.21,0.00,59924.84,111.41,upi,Delivered,1.3,52835.48,6977.95
4,ORD300005,CUST103419,PROD227767,2025-04-26 18:21:41,4,25221.66,0.10,90797.98,39.97,net banking,Delivered,1.5,86114.24,4643.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD349996,CUST121839,PROD208790,2025-09-15 04:12:28,5,18577.66,0.05,88243.88,161.74,Net Banking,Delivered,3.9,74204.15,13877.99
49996,ORD349997,CUST112544,PROD213782,2026-04-09 08:08:45,4,5568.52,0.15,18932.97,106.52,Debit Card,Delivered,3.0,18486.28,340.17
49997,ORD349998,CUST114304,PROD210200,2024-07-16 07:47:43,3,524.00,0.00,1572.00,124.52,Credit Card,Delivered,2.1,1446.06,1.42
49998,ORD349999,CUST111905,PROD224118,2025-12-21 02:14:06,4,12904.25,0.15,43874.45,162.03,Wallet,Delivered,2.0,45853.56,-2141.14
49999,ORD350000,CUST147545,PROD222045,2026-05-10 04:43:21,5,4121.26,0.15,17515.36,41.19,Wallet,Delivered,1.8,16242.30,1231.87

In [27]:
orders[
    (orders["customer_rating"] < 1) |
    (orders["customer_rating"] > 5)
]

Empty DataFrame
Columns: [order_id, customer_id, product_id, order_date, quantity, unit_price, discount_pct, revenue, shipping_cost, payment_method, order_status, customer_rating, estimated_cost, profit]
Index: []

10. Realtionship Validation

In [29]:
invalid_customers = orders[~orders["product_id"].isin(products["product_id"])]
print(invalid_customers)

Empty DataFrame
Columns: [order_id, customer_id, product_id, order_date, quantity, unit_price, discount_pct, revenue, shipping_cost, payment_method, order_status, customer_rating, estimated_cost, profit]
Index: []

11. Category Consistency

In [30]:
orders["payment_method"].value_counts(dropna=False)

payment_method
Net Banking    8494
UPI            8360
Credit Card    8339
Wallet         8268
COD            8245
Debit Card     8144
credit card      33
debit card       29
cod              25
upi              25
net banking      19
wallet           19
Name: count, dtype: int64

In [49]:
products["sub_category"].value_counts(dropna=False)

sub_category
Personal Care     1334
Haircare          1321
Fiction           1309
Beverages         1305
Accessories       1296
Technology        1296
Outdoor           1291
Cycling           1286
Education         1284
Furniture         1280
Appliances        1279
Yoga              1274
Skincare          1273
Makeup            1273
Watches           1272
Business          1271
Bags              1269
Snacks            1268
Kitchen           1250
Footwear          1247
Decor             1245
Men               1243
Staples           1233
Puzzles           1233
Household         1231
Smartphones       1230
Fitness           1228
Women             1228
Comics            1225
Laptops           1222
Storage           1222
Games             1221
Organic           1219
Action Figures    1213
Headphones        1209
Cricket           1207
Outdoor Toys      1202
Smartwatches      1172
Educational       1172
Fragrance         1167
Name: count, dtype: int64

12. Date Inspection

In [31]:
orders["order_date"].min()
orders["order_date"].max()

'2026-08-30 23:41:38'

In [32]:
orders["order_date"].isna().sum()

np.int64(0)

13. Inavlid Values Inspectiion

In [45]:
import pandas as pd

invalid_records = []


inv_cost = (datasets['Products']['cost_price'] <= 0).sum()
invalid_records.append({
    'Dataset': 'Products',
    'Column': 'cost_price',
    'Issue': 'Negative cost price (<= 0)',
    'Count': inv_cost,
})


inv_qty = (datasets['Orders']['quantity'] <= 0).sum()
invalid_records.append({
    'Dataset': 'Orders',
    'Column': 'quantity',
    'Issue': 'Negative quantity (<= 0)',
    'Count': inv_qty,
})


inv_sold = (datasets['Inventory']['units_sold'] < 0).sum()
invalid_records.append({
    'Dataset': 'Inventory',
    'Column': 'units_sold',
    'Issue': 'Negative units sold (< 0)',
    'Count': inv_sold,
})


inv_gender_space = (
    datasets['Customers']['gender']
    .str.contains('^\s+|\s+$', regex=True)
    .sum()
)
invalid_records.append({
    'Dataset': 'Customers',
    'Column': 'gender',
    'Issue': 'Leading/trailing whitespace',
    'Count': inv_gender_space,
})



# Display summary dataframe
invalid_summary_df = pd.DataFrame(invalid_records)
display(invalid_summary_df)

<>:35: SyntaxWarning: invalid escape sequence '\s'
<>:35: SyntaxWarning: invalid escape sequence '\s'
C:\Users\ranja\AppData\Local\Temp\ipykernel_21860\1260526643.py:35: SyntaxWarning: invalid escape sequence '\s'
  .str.contains('^\s+|\s+$', regex=True)

     Dataset      Column                        Issue  Count
0   Products  cost_price   Negative cost price (<= 0)    200
1     Orders    quantity     Negative quantity (<= 0)    150
2  Inventory  units_sold    Negative units sold (< 0)    200
3  Customers      gender  Leading/trailing whitespace    120

creation of 2nd table

In [47]:
import pandas as pd


missing_customer_id = datasets['Orders']['customer_id'].isnull().sum()


negative_quantity = (datasets['Orders']['quantity'] < 0).sum()


duplicate_order_id = datasets['Orders']['order_id'].duplicated().sum()


missing_rating = datasets['Orders']['customer_rating'].isnull().sum()


invalid_stock_products = datasets['Products']['stock_quantity'].isnull().sum()
invalid_stock_inventory = (
    datasets['Inventory']['closing_stock'].isnull().sum()
)


check_results = pd.DataFrame([
    {
        'Issue Checklist': 'Missing Customer ID',
        'Dataset': 'Orders',
        'Column': 'customer_id',
        'Count': missing_customer_id,
    },
    {
        'Issue Checklist': 'Negative Quantity',
        'Dataset': 'Orders',
        'Column': 'quantity',
        'Count': negative_quantity,
    },
    {
        'Issue Checklist': 'Duplicate Order ID',
        'Dataset': 'Orders',
        'Column': 'order_id',
        'Count': duplicate_order_id,
    },
    {
        'Issue Checklist': 'Missing Rating',
        'Dataset': 'Orders',
        'Column': 'customer_rating',
        'Count': missing_rating,
    },
    {
        'Issue Checklist': 'Invalid/Missing Stock',
        'Dataset': 'Products',
        'Column': 'stock_quantity',
        'Count': invalid_stock_products,
    },
    {
        'Issue Checklist': 'Invalid/Missing Stock',
        'Dataset': 'Inventory',
        'Column': 'closing_stock',
        'Count': invalid_stock_inventory,
    },
])

display(check_results)

         Issue Checklist    Dataset           Column  Count
0    Missing Customer ID     Orders      customer_id    150
1      Negative Quantity     Orders         quantity    150
2     Duplicate Order ID     Orders         order_id      0
3         Missing Rating     Orders  customer_rating    300
4  Invalid/Missing Stock   Products   stock_quantity    300
5  Invalid/Missing Stock  Inventory    closing_stock    250